name: 'Giphy PR Comment'
description: 'Add a Giphy GIF comment to new pull requests.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: # these arguments are passed into the entrypoint.sh script in $GITHUB_TOKEN and $GIPHY_API_KEY
    - ${{ inputs.github-token }}
    - ${{ inputs.giphy-api-key }}